@startuml System Architecture

[API Gateway (JS)] as AG
database "Cache" as CACHE
[Service Discovery (JS)] as SD

[User Service (Python)] as US
database "User DB" as UDB

[Tweet Service (Python)] as TS
database "Tweet DB" as TDB

package "ELK Stack" {
  [Logstash] as LS
  database "Elastic Storage" as ES
  [Kibana] as K
}

US <-right-> TS

AG -left- CACHE
AG --> US : API
AG --> TS : API
AG .right.> SD

SD <.. US
SD <.. TS

TS -down-> LS  : Logs
US -right-> LS : Logs

US -down- UDB
TS -down- TDB

LS --> ES : Processed Logs
ES --> K : Data

@enduml
