{
 "title": "Requests Status Code",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Successful Requests",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (http_requests_total{code=\"200\"}) + sum by (instance) (http_requests_total{code=\"304\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bad Requests",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{code=\"400\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Found Requests",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{code=\"404\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal Server Error Requests",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{code=\"500\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}